CREATE TABLE countries
(
    id   int GENERATED BY DEFAULT AS IDENTITY primary key,
    title varchar(255)
);

CREATE TABLE users
(
    id         int GENERATED BY DEFAULT AS IDENTITY primary key,
    name       varchar(255),
    country_id int REFERENCES countries (id)
);

INSERT INTO countries
values (DEFAULT, 'Country1'),
       (DEFAULT, 'Country2'),
       (DEFAULT, 'Country3');

INSERT INTO users
values (DEFAULT, 'Name1', 3),
       (DEFAULT, 'Name2', 2),
       (DEFAULT, 'Name3', 1);

SELECT u.id, u.name, c.title
FROM users as u
         LEFT JOIN countries c on u.country_id = c.id;