CREATE TABLE owners
(
    id   int generated by default as identity primary key,
    name varchar(255)
);

CREATE TABLE books
(
    id    int generated by default as identity primary key,
    title varchar(255),
    owner int REFERENCES owners (id)
);

INSERT INTO owners
values (DEFAULT, 'Owner1'),
       (DEFAULT, 'Owner2');

INSERT INTO books
values (DEFAULT, 'Book1', 1),
       (DEFAULT, 'Book2', 2),
       (DEFAULT, 'Book3', 1),
       (DEFAULT, 'Book4', 2);