CREATE TABLE students
(
    id   int generated by default as identity primary key,
    name varchar(255)
);

INSERT INTO students
values (DEFAULT, 'Name1');
INSERT INTO students
values (DEFAULT, 'Name2');